version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "49000:49000"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-network
    command: --httpPort=49000
  nginx:
    image: nginx:latest
    container_name: nginx-jenkins
    ports:
      - "9000:9000"
    volumes:
      - ./nginx-jenkins/conf.d:/etc/nginx/conf.d
    networks:
      - jenkins-network
    depends_on:
      - jenkins

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins_home:
