version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "49000:49000"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-network
      - monitoring-network
    command: --httpPort=49000

  nginx:
    image: nginx:latest
    container_name: nginx-jenkins
    ports:
      - "9000:9000"
    volumes:
      - ./nginx-jenkins/conf.d:/etc/nginx/conf.d
    networks:
      - jenkins-network
    depends_on:
      - jenkins

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - NO_PROXY=localhost,127.0.0.1,prometheus
      - no_proxy=localhost,127.0.0.1,prometheus
    networks:
      - monitoring-network
    depends_on:
      - prometheus

networks:
  jenkins-network:
    driver: bridge
  monitoring-network:
    driver: bridge

volumes:
  jenkins_home:
  prometheus_data:
  grafana_data:
