global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    basic_auth:
      username: 'dicoding'
      password: 'admin123'
    static_configs:
      - targets: ['jenkins-blueocean:8080']
